language: node_js
node_js:
  - 12

services:
  - docker

script:
  - docker --version
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag udagram-api-user lucastannus/udagram-api-user:v1
  - docker tag udagram-api-feed lucastannus/udagram-api-feed:v1
  - docker tag udagram-frontend:local lucastannus/udagram-frontend:v1
  - docker tag reverseproxy lucastannus/reverseproxy:v1

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push lucastannus/udagram-api-user:v1
  - docker push lucastannus/udagram-api-feed:v1
  - docker push lucastannus/udagram-frontend:v1
  - docker push lucastannus/reverseproxy:v1
